
server:
  port: 8090
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}
    key-alias: "ncookiessl"

spring:
  application:
    name: spring-boot-admin-server
  security:
    user:
      name: ${ADMIN_SERVER_USERNAME}
      password: ${ADMIN_SERVER_PASSWORD}
  boot:
    admin:
      ui:
        poll-timer:
          logfile: 30000    # logfile ?? ??. 30?? ???
